// import { getAge,getName } from './student';
// const s1 = require("./student")
const {getName,getAge,cgpa} = require("./student")
console.log("hello world")
// console.log(s1.getName)
// console.log(s1.getName())
// console.log(s1.getAge)
// console.log(s1.getAge())
// // console.log(s1.result)
// console.log(s1.cgpa)
console.log(getName)
console.log(getName())
console.log(getAge())
console.log(cgpa)